title: Adri치n L칩pez Sole # your name (or website title) here
logo: "/images/perfil_1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <br><br>
  "Aunque mi pasi칩n es la informaci칩n"
  <br><br>
  <a href="https://www.linkedin.com/in/adrianlopezsoler/" target="_blank">LinkedIn</a>
  -
  <a href="https://www.instagram.com/adriantimes/" target="_blank">Instagram</a>
  -
  <a href="https://www.twitter.com/adrilopezsoler/" target="_blank">Twitter</a>
  -
  <a href="https://www.medium.com/@adrianlopezsoler/" target="_blank">Medium</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
